# version: '3.8'  <-- pode remover ou comentar
services:
  db:
    image: postgres:15
    container_name: polaris-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwordd
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
